# Generated by Django 2.2.1 on 2019-05-13 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('max_passengers', models.PositiveIntegerField()),
                ('production_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2019)])),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Economy', 'Ekonomiczna'), ('Business', 'Biznesowa'), ('First', 'Pierwsza')], max_length=100)),
                ('engine_type', models.CharField(blank=True, choices=[('Petrol', 'Benzyna/Diesel'), ('Hybrid', 'Hybrydowy'), ('Electrical', 'Elektryczny')], default='Petrol', max_length=100)),
            ],
        ),
    ]
