# Generated by Django 2.2.1 on 2019-05-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Ekonomiczna', 'Ekonomiczna'), ('Biznesowa', 'Biznesowa'), ('Pierwsza', 'Pierwsza')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('Benzyna/Diesel', 'Benzyna/Diesel'), ('Hybrydowy', 'Hybrydowy'), ('Elektryczny', 'Elektryczny')], default='Benzyna/Diesel', max_length=100),
        ),
    ]
